/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsRevenuecatRouteImport } from './routes/api/public/payments/revenuecat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsRevenuecatRoute =
  ApiPublicPaymentsRevenuecatRouteImport.update({
    id: '/api/public/payments/revenuecat',
    path: '/api/public/payments/revenuecat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/u/$id': typeof UIdRoute
  '/api/public/payments/revenuecat': typeof ApiPublicPaymentsRevenuecatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/u/$id': typeof UIdRoute
  '/api/public/payments/revenuecat': typeof ApiPublicPaymentsRevenuecatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/u/$id': typeof UIdRoute
  '/api/public/payments/revenuecat': typeof ApiPublicPaymentsRevenuecatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/delete-account'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/plan'
    | '/routes'
    | '/settings'
    | '/community/$id'
    | '/u/$id'
    | '/api/public/payments/revenuecat'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/delete-account'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/plan'
    | '/routes'
    | '/settings'
    | '/community/$id'
    | '/u/$id'
    | '/api/public/payments/revenuecat'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community'
    | '/delete-account'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/_authenticated/plan'
    | '/_authenticated/routes'
    | '/_authenticated/settings'
    | '/community/$id'
    | '/u/$id'
    | '/api/public/payments/revenuecat'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  UIdRoute: typeof UIdRoute
  ApiPublicPaymentsRevenuecatRoute: typeof ApiPublicPaymentsRevenuecatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/revenuecat': {
      id: '/api/public/payments/revenuecat'
      path: '/api/public/payments/revenuecat'
      fullPath: '/api/public/payments/revenuecat'
      preLoaderRoute: typeof ApiPublicPaymentsRevenuecatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  UIdRoute: UIdRoute,
  ApiPublicPaymentsRevenuecatRoute: ApiPublicPaymentsRevenuecatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
