// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { executeProductionSupabaseAuthMiddleware } from "./auth-boundary.server";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();
    return executeProductionSupabaseAuthMiddleware({
      request,
      next: (verified) =>
        next({
          context: {
            supabase: verified.supabase,
            userId: verified.userId,
            claims: verified.claims,
          },
        }),
    });
  },
);
